### Site metadata

# Don't make the title longer than this, otherwise it gets covered in mobile view.
title: My Blog
description: Starter for a static website or blog - built with Jekyll, a minimal theme and GH Pages

email:
twitter_username:
github_username: globulion
rss: RSS

### Build settings

url: https://globulion.github.io
baseurl: /main

permalink: pretty

theme: minima

plugins:
  - jekyll-feed
  - jekyll-sitemap

collections:
  tools:
    output: true
  languages:
    output: true

defaults:
  - scope:
      path: ""
    values:
      layout: page

exclude:
  - docs/
  - vendor/
  - Gemfile # Gemfile.lock is implied because of how matching works.
  - LICENSE
  - Makefile
  - README.md
  - sample*.png

liquid:
  error_mode: strict

strict_front_matter: true
