### Site metadata

# Don't make the title longer than this, otherwise it gets covered in mobile view.
title: Bartosz Blasiak
description: Theoretical chemistry of condensed phased systems

email:
twitter_username:
github_username: globulion
rss: RSS

### Build settings

url: https://globulion.github.io
#baseurl: /

permalink: pretty

theme: minima
#remote_theme: pages-themes/minimal@v0.2.0

plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-remote-theme # add this line to the plugins list if you already have one

collections:
  tools:
    output: true
  languages:
    output: true

defaults:
  - scope:
      path: ""
    values:
      layout: page

exclude:
  - docs/
  - vendor/
  - Gemfile # Gemfile.lock is implied because of how matching works.
  - LICENSE
  - Makefile
  - README.md
  - sample*.png

liquid:
  error_mode: strict

strict_front_matter: true
